### ISSUE TITLE
The number of objects

### ISSUE THREAD

**Issue by kimkj38** [he-dhamo/graphto3d#10]
Hello, I hope to combine 3DSSG and oriented bounding box you annotated on the paper.

But the number of objects for same scan doesn't match.

For example, 3DSSG has 30 objects but yours has 25 objects. And I don't understand why the id is not in order(like 35->37->50)

Could you explain about it?
<img width="591" alt="ObjectMatch" src="https://user-images.githubusercontent.com/76815825/182769381-d164befa-136b-4c03-9265-bfd83504e0af.png">

**Comment by he-dhamo** [comment]
Hello, this is because we work with the subset from 3DSSG (used for the learning methods introduced in the 3DSSG paper). For instance, the subset discards instances from 3RScan that are from an under-represented class, i.e. works with 160 object classes instead of around 500 in the original set. The gaps in our instance ids are there so that the correspondence with the original ids from the full 3DSSG are kept, for example object instance 37 in the graph-to-3d data is the same as object instance 37 in the full 3DSSG data. For the missing ids (e.g. 36) there is no oriented box annotation.

**Comment by kimkj38** [comment]
@he-dhamo Thanks for your reply!

**Comment by kimkj38** [comment]
@he-dhamo In the picture above, the final index of 3DSSG is 29 but graph to 3D has id greater than 29(30,31, ..., 50). I checked other scans and found same problems. How can i match them?
